import type { MLModule } from '../../types';

export const gradientBoosting: MLModule = {
  "id": "gradient-boosting",
  "title": "Gradient Boosting & XGBoost",
  "category": "Supervised Learning",
  "description": "Ensemble weak learners sequentially by fitting residuals to correct past errors.",
  "formula": "F_m(x) = F_{m-1}(x) + \\gamma_m h_m(x)",
  "theory": `### What is Gradient Boosting?

Gradient Boosting is an advanced, highly effective ensemble machine learning algorithm utilized extensively for both complex regression and classification problems. Unlike Random Forests, which build numerous independent decision trees in parallel (a technique known as bagging) to average out variance, Gradient Boosting adopts a sequential methodology (boosting). It constructs trees one at a time, where each new tree in the ensemble is explicitly trained to correct the errors—the residuals—made by the combined predictions of all the previously built trees. This creates a remarkably strong predictive model from a collection of weak learners.

### Why do we need it?

Gradient Boosting is renowned for frequently achieving state-of-the-art performance on structured, tabular datasets, routinely outperforming sophisticated deep neural networks and standard Random Forests in Kaggle competitions and real-world enterprise applications. It offers immense flexibility because it can be tailored to optimize virtually any differentiable loss function, whether for regression, classification, or ranking. It natively handles missing data, naturally provides feature importance scores, and forms the core theoretical backbone for highly optimized, industry-standard libraries such as XGBoost, LightGBM, and CatBoost.

### How does it work?

The operational mechanics of Gradient Boosting follow a logical, step-by-step sequential optimization process:
1. **Initialization:** The algorithm kicks off with a naive, constant baseline prediction. For regression, this is typically the mean of the target variable; for binary classification, it is the log-odds of the positive class.
2. **Calculate Residuals:** In every subsequent iteration, the model calculates the "pseudo-residuals" for all data points. These are the discrepancies between the actual target values and the current ensemble's predictions. Mathematically, these represent the negative gradient of the loss function.
3. **Train a Weak Learner:** A weak learner—most commonly a shallow Decision Tree with a small maximum depth (e.g., 3 to 6)—is trained to predict these pseudo-residuals rather than the original target values.
4. **Update Predictions:** The predictions generated by this new tree are scaled down by a learning rate parameter (often called shrinkage) and then added to the cumulative predictions of the ensemble.
5. **Iterate:** Steps 2 through 4 are repeated for hundreds or thousands of iterations until a specified maximum number of trees is reached, or until the validation error ceases to improve (early stopping).

### The Math Behind It

#### General Boosting Equation
An ensemble consisting of $M$ estimators formulates its final prediction as:
$$F_M(x) = F_0(x) + \sum_{m=1}^{M} \gamma_m h_m(x)$$
Where $F_0(x)$ acts as the initial guess, $h_m(x)$ denotes the $m$-th weak learner (tree), and $\gamma_m$ is the learning rate governing the tree's contribution.

#### Residual Fitting (Gradient Descent in Function Space)
In any given step $m$, the objective is to find a tree $h_m$ that minimizes the overall loss $L$:
$$h_m = \arg\min_h \sum_{i=1}^n L(y_i, F_{m-1}(x_i) + h(x_i))$$
By employing a first-order Taylor approximation, fitting $h_m$ becomes mathematically equivalent to training the tree on the pseudo-residuals, which represent the negative gradient of the loss function:
$$r_{im} = -\left[ \frac{\partial L(y_i, F(x_i))}{\partial F(x_i)} \right]_{F(x) = F_{m-1}(x)}$$

#### XGBoost Optimizations (Newton Boosting)
XGBoost significantly advances standard Gradient Boosting by utilizing a second-order Taylor expansion—incorporating both gradients (first derivatives) and Hessians (second derivatives)—to optimize node splits vastly faster and with greater precision:
$$\mathcal{L}^{(t)} \approx \sum_{i=1}^{n} \left[ g_i f_t(x_i) + \frac{1}{2} h_i f_t^2(x_i) \right] + \Omega(f_t)$$
Where $g_i$ represents the gradient, $h_i$ represents the Hessian, and $\Omega(f_t) = \gamma T + \frac{1}{2} \lambda \sum w_j^2$ acts as a stringent regularization term. This term actively penalizes excessive tree complexity ($T$ leaves and $w$ leaf weights) to strictly prevent the model from overfitting the noise in the training data.

### Worked Example

Imagine predicting the price of a house whose true market value is $\$200$k.
1. **Initial prediction:** The average house price across your entire dataset is $\$150$k. Your initial error (the residual) is $\$200$k - $\$150$k = $\$50$k.
2. **Tree 1:** The very first tree is trained exclusively to predict this $\$50$k residual. Let's assume it predicts $\$40$k.
3. **Update:** We apply a conservative learning rate of 0.1. The new ensemble prediction becomes: $\$150$k + (0.1 $\times \$40$k) = $\$154$k.
4. **New Residual:** The updated residual shrinks to: $\$200$k - $\$154$k = $\$46$k.
5. **Tree 2:** The second tree attempts to predict this new $\$46$k residual. It predicts $\$45$k.
6. **Update:** The new ensemble prediction is: $\$154$k + (0.1 $\times \$45$k) = $\$158.5$k.

This meticulous, iterative process continues, slowly inching towards the true target of $\$200$k. The small learning rate explicitly prevents the model from drastically over-correcting, acting as a crucial safeguard against overfitting.

### Common Pitfalls

1. **Overfitting:** Because Gradient Boosting actively and aggressively minimizes training error, running it for too many iterations (trees) without early stopping will inevitably cause it to memorize the training data, leading to severe overfitting.
2. **Hyperparameter Sensitivity:** The model\'s performance is critically dependent on careful tuning of parameters. The \`learning_rate\` and \`n_estimators\` are inversely correlated, and \`max_depth\` must be kept small.
3. **Training Speed:** Standard GBM trains trees sequentially, meaning the tree-building process itself cannot be naturally parallelized at the macro level (unlike Random Forests). This makes it computationally expensive on massive datasets, although libraries like XGBoost cleverly parallelize the internal split-finding mechanics.

### When to Use vs Not Use

**When to Use:**
- On structured/tabular datasets where it is historically proven to be the most accurate algorithm available.
- When you possess the computational resources and time to extensively tune its numerous hyperparameters.
- In highly competitive scenarios (like Kaggle competitions) or business cases prioritizing raw predictive accuracy above all else.

**When Not to Use:**
- On highly dimensional unstructured data (e.g., raw images, audio, long-form text), domains where deep learning models are fundamentally superior.
- When lightning-fast training times and real-time model updates (online learning) are absolute requirements.
- When absolute model interpretability—such as presenting a single, easily digestible visual tree to stakeholders—is required, as the large ensemble acts essentially as a "black box."

### Key Takeaways
- Gradient Boosting trains a sequence of shallow, high-bias trees to methodically correct the aggregated errors of prior trees.
- It elegantly translates the concept of boosting into a gradient descent optimization problem occurring in function space rather than parameter space.
- The learning rate directly scales individual tree contributions, acting as a vital regularizer that requires more trees but yields better generalization.
- Advanced framework implementations like XGBoost and LightGBM leverage second-order derivatives and strict architectural regularization to achieve unmatched, state-of-the-art tabular performance.`,
  "interactiveSummary": "This simulator visualizes the sequential ensemble-building process of Gradient Boosting step by step. Each iteration adds a new shallow decision tree trained exclusively on the pseudo-residuals — the negative gradient of the loss — left by the current ensemble, progressively correcting errors rather than fitting the original targets. The residual panel shows how the magnitude of remaining errors shrinks with each boosting round, while the prediction curve converges toward the true function. Adjusting the learning rate (shrinkage) controls how aggressively each tree's contribution is scaled: lower values produce a smoother, more regularized fit at the cost of requiring more trees. Toggle between MSE and Log-loss objectives to observe how the pseudo-residual formula changes, connecting the algorithm's math directly to its visual behavior.",
  "simulatorId": "gradient-boosting",
  "quiz": [
    {
      "id": "gb_q1",
      "question": "What is the primary mechanism of Gradient Boosting?",
      "options": [
        "Training many deep trees independently and averaging them",
        "Training shallow trees sequentially, where each new tree fits the errors of the previous ensemble",
        "Using a single deep tree and pruning it",
        "Updating weights of misclassified samples randomly"
      ],
      "correctAnswer": "Training shallow trees sequentially, where each new tree fits the errors of the previous ensemble",
      "explanation": "Gradient Boosting builds an ensemble additively, adding one tree at a time that specifically targets the pseudo-residuals (negative gradient) left by the current model."
    },
    {
      "id": "gb_q2",
      "question": "What is the role of the learning rate (shrinkage parameter) in Gradient Boosting?",
      "options": [
        "It increases the depth of the trees",
        "It scales the contribution of each newly added tree, acting as a regularizer",
        "It determines the proportion of features used in a split",
        "It controls the number of trees built"
      ],
      "correctAnswer": "It scales the contribution of each newly added tree, acting as a regularizer",
      "explanation": "The learning rate (< 1.0) shrinks the predictions of each tree before adding them. This requires more trees to be added, but significantly slows down overfitting."
    },
    {
      "id": "gb_q3",
      "question": "How does XGBoost differ from traditional Gradient Boosting Machines (GBM)?",
      "options": [
        "XGBoost builds trees in parallel instead of sequentially",
        "XGBoost uses second-order derivatives (Hessians) and explicit regularization in its objective function",
        "XGBoost uses Neural Networks instead of Decision Trees",
        "XGBoost does not use a learning rate"
      ],
      "correctAnswer": "XGBoost uses second-order derivatives (Hessians) and explicit regularization in its objective function",
      "explanation": "XGBoost employs a second-order Taylor expansion of the loss function and adds L1/L2 penalties on leaf weights and tree complexity, making it faster and more robust."
    },
    {
      "id": "gb_q4",
      "question": "Why does a Gradient Boosting model become more prone to overfitting as 'n_estimators' increases?",
      "options": [
        "Because each tree becomes deeper",
        "Because it relies on bagging",
        "Because it continually reduces training error by fitting the residual noise in the data",
        "Because the learning rate increases automatically"
      ],
      "correctAnswer": "Because it continually reduces training error by fitting the residual noise in the data",
      "explanation": "Unlike Random Forests, adding more trees in boosting will eventually cause the model to perfectly memorize the training set, including its noise."
    },
    {
      "id": "gb_q5",
      "question": "If you decrease the learning rate in Gradient Boosting, what must you typically do to maintain model performance?",
      "options": [
        "Decrease the maximum tree depth",
        "Increase the number of trees (n_estimators)",
        "Decrease the number of features used",
        "Switch to an L1 loss function"
      ],
      "correctAnswer": "Increase the number of trees (n_estimators)",
      "explanation": "A smaller learning rate means each tree contributes less. Therefore, you need more trees to achieve the same level of training."
    },
    {
      "id": "gb_q6",
      "question": "What are the 'pseudo-residuals' in Gradient Boosting?",
      "options": [
        "The negative gradient of the loss function with respect to the model\'s current predictions",
        "The raw difference between the mean and the median",
        "The absolute values of the errors",
        "The weights of the leaves in the first tree"
      ],
      "correctAnswer": "The negative gradient of the loss function with respect to the model\'s current predictions",
      "explanation": "For any differentiable loss function, the algorithm fits the new tree to the negative gradient of the loss, which generalizes the concept of residuals."
    },
    {
      "id": "gb_q7",
      "question": "Which hyperparameter is typically used to control the complexity of the individual trees (weak learners) in Gradient Boosting?",
      "options": [
        "n_estimators",
        "learning_rate",
        "max_depth",
        "subsample"
      ],
      "correctAnswer": "max_depth",
      "explanation": "max_depth limits how deep the individual decision trees can grow. In boosting, weak learners are usually shallow trees (e.g., depth 3 to 6)."
    },
    {
      "id": "gb_q8",
      "question": "What does Stochastic Gradient Boosting involve?",
      "options": [
        "Randomizing the loss function at each step",
        "Subsampling the training data or features before training each new tree",
        "Adding random Gaussian noise to the targets",
        "Replacing trees with linear regressions"
      ],
      "correctAnswer": "Subsampling the training data or features before training each new tree",
      "explanation": "Stochastic Gradient Boosting borrows from Random Forests by using a random subset of data (row subsampling) and/or features (column subsampling) for each tree, which reduces variance."
    },
    {
      "id": "gb_q9",
      "question": "For a Mean Squared Error (MSE) loss, what do the pseudo-residuals equal?",
      "options": [
        "The sign of the error",
        "The true target values",
        "The exact difference between the true target and the predicted value (y_true - y_pred)",
        "The predicted values squared"
      ],
      "correctAnswer": "The exact difference between the true target and the predicted value (y_true - y_pred)",
      "explanation": "The derivative of MSE = 0.5 * (y - F)^2 with respect to F is -(y - F). The negative gradient is therefore exactly y - F, which is the standard residual."
    },
    {
      "id": "gb_q10",
      "question": "What is the purpose of 'Early Stopping' in Gradient Boosting?",
      "options": [
        "To stop training when the learning rate reaches zero",
        "To stop adding trees when the performance on a validation dataset stops improving",
        "To halt the growth of a single tree before it reaches max_depth",
        "To prevent the calculation of Hessians"
      ],
      "correctAnswer": "To stop adding trees when the performance on a validation dataset stops improving",
      "explanation": "Early stopping monitors validation loss during the sequential addition of trees. If the loss hasn't improved for a specified number of rounds, training stops to prevent overfitting."
    }
  ],
  "coding": {
    "tutorial": {
      "title": "Calculate Pseudo-Residuals",
      "description": "Calculate the pseudo-residuals for a regression task with Squared Error loss. In sklearn, GradientBoostingRegressor computes this automatically under the hood.",
      "pseudoCode": "function get_residuals(y_true, y_pred):\n    return y_true - y_pred",
      "starterCode": "import numpy as np\n\ndef get_residuals(y_true, y_pred):\n    # TODO: Calculate residuals (negative gradient of squared error)\n    return np.array([])\n\ny_t = np.array([10.0, 15.0, 12.0])\ny_p = np.array([9.5, 15.5, 11.0])\nprint(\"Residuals:\", get_residuals(y_t, y_p))",
      "expectedOutput": "Residuals: [ 0.5 -0.5  1. ]",
      "solution": "import numpy as np\n\ndef get_residuals(y_true, y_pred):\n    return y_true - y_pred\n\ny_t = np.array([10.0, 15.0, 12.0])\ny_p = np.array([9.5, 15.5, 11.0])\nprint(\"Residuals:\", get_residuals(y_t, y_p))",
      "hints": [
        "Subtract y_pred from y_true."
      ],
      "testKeywords": [
        "y_true - y_pred"
      ]
    },
    "project": {
      "title": "Credit Risk Prediction with Gradient Boosting",
      "description": "Build a credit risk classifier using `GradientBoostingClassifier` on financial features (annual_income, debt_ratio, num_late_payments, credit_utilization). Predict whether a loan applicant is high-risk (1) or low-risk (0), then report accuracy and feature importances.",
      "pseudoCode": "# Credit Risk Gradient Boosting\nIMPORT GradientBoostingClassifier, make_pipeline, StandardScaler, accuracy_score\n\n# Features: [annual_income, debt_ratio, num_late_payments, credit_utilization]\nDEFINE X with 10 applicants covering varied financial profiles\nDEFINE y as binary labels (1=high-risk, 0=low-risk)\n\nCREATE pipeline with StandardScaler and GradientBoostingClassifier(\n    n_estimators=50, learning_rate=0.1, max_depth=3, random_state=42)\nFIT pipeline on X, y\nPREDICT on X\nCOMPUTE accuracy_score(y, predictions)\nEXTRACT feature_importances_ from the GBC step\nPRINT accuracy rounded to 2 decimals\nPRINT feature importances rounded to 3 decimals",
      "starterCode": "import numpy as np\nfrom sklearn.ensemble import GradientBoostingClassifier\nfrom sklearn.pipeline import make_pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.metrics import accuracy_score\n\n# Financial features: [annual_income($k), debt_ratio, num_late_payments, credit_utilization(%)]\nX = np.array([\n    [85, 0.15, 0, 22],   # low-risk\n    [42, 0.72, 5, 87],   # high-risk\n    [120, 0.10, 0, 15],  # low-risk\n    [35, 0.85, 8, 91],   # high-risk\n    [95, 0.20, 1, 30],   # low-risk\n    [28, 0.90, 12, 95],  # high-risk\n    [110, 0.12, 0, 18],  # low-risk\n    [50, 0.65, 4, 75],   # high-risk\n    [78, 0.25, 0, 28],   # low-risk\n    [33, 0.80, 9, 88],   # high-risk\n])\ny = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])\n\n# TODO: Create pipeline with StandardScaler and GradientBoostingClassifier\n#       (n_estimators=50, learning_rate=0.1, max_depth=3, random_state=42)\n# TODO: Fit the pipeline, predict on X, compute accuracy\n# TODO: Extract feature importances from the GradientBoostingClassifier step\nclf = None\npredictions = np.array([])\nacc = 0.0\nimportances = np.array([])\n\nprint(f\"Accuracy: {round(acc, 2)}\")\nprint(\"Feature Importances:\", np.round(importances, 3))",
      "expectedOutput": "Accuracy: 1.0\nFeature Importances: [0.    0.234 0.544 0.222]",
      "solution": "import numpy as np\nfrom sklearn.ensemble import GradientBoostingClassifier\nfrom sklearn.pipeline import make_pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.metrics import accuracy_score\n\nX = np.array([\n    [85, 0.15, 0, 22],\n    [42, 0.72, 5, 87],\n    [120, 0.10, 0, 15],\n    [35, 0.85, 8, 91],\n    [95, 0.20, 1, 30],\n    [28, 0.90, 12, 95],\n    [110, 0.12, 0, 18],\n    [50, 0.65, 4, 75],\n    [78, 0.25, 0, 28],\n    [33, 0.80, 9, 88],\n])\ny = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])\n\nclf = make_pipeline(StandardScaler(), GradientBoostingClassifier(n_estimators=50, learning_rate=0.1, max_depth=3, random_state=42))\nclf.fit(X, y)\npredictions = clf.predict(X)\nacc = accuracy_score(y, predictions)\nimportances = clf.named_steps['gradientboostingclassifier'].feature_importances_\n\nprint(f\"Accuracy: {round(acc, 2)}\")\nprint(\"Feature Importances:\", np.round(importances, 3))",
      "hints": [
        "Use make_pipeline(StandardScaler(), GradientBoostingClassifier(n_estimators=50, learning_rate=0.1, max_depth=3, random_state=42))",
        "Access feature importances via clf.named_steps['gradientboostingclassifier'].feature_importances_",
        "Call fit() then predict(), then accuracy_score(y, predictions)"
      ],
      "testKeywords": [
        "make_pipeline",
        "GradientBoostingClassifier",
        "feature_importances_",
        "fit",
        "predict",
        "accuracy_score"
      ]
    },
    "assignment": {
      "title": "Energy Consumption Forecasting with Gradient Boosting",
      "description": "Use `GradientBoostingRegressor` to predict hourly building energy consumption (kWh) from weather and time features: [temperature_C, humidity_pct, hour_of_day, is_weekend]. Evaluate with 5-fold cross-validation and report mean R² score and RMSE.",
      "pseudoCode": "# Energy Consumption Forecasting\nIMPORT GradientBoostingRegressor, cross_val_score, mean_squared_error\n\n# Features: [temperature_C, humidity_pct, hour_of_day, is_weekend]\nDEFINE X with 20 hourly readings\nDEFINE y as energy consumption in kWh\n\nINITIALIZE model = GradientBoostingRegressor(\n    n_estimators=100, learning_rate=0.05, max_depth=4,\n    subsample=0.8, random_state=42)\n\nCOMPUTE r2_scores = cross_val_score(model, X, y, cv=5, scoring='r2')\nFIT model on full X, y\nCOMPUTE predictions = model.predict(X)\nCOMPUTE rmse = sqrt(mean_squared_error(y, predictions))\n\nPRINT mean R2 rounded to 2 decimals\nPRINT RMSE rounded to 2 decimals",
      "starterCode": "import numpy as np\nfrom sklearn.ensemble import GradientBoostingRegressor\nfrom sklearn.model_selection import cross_val_score\nfrom sklearn.metrics import mean_squared_error\n\n# Features: [temperature_C, humidity_pct, hour_of_day, is_weekend]\nrng = np.random.RandomState(42)\nX = np.column_stack([\n    rng.uniform(15, 35, 60),   # temperature_C\n    rng.uniform(30, 90, 60),   # humidity_pct\n    np.tile(np.arange(24), 3)[:60],  # hour_of_day (0-23)\n    np.tile([0,0,0,0,0,1,1], 9)[:60] # is_weekend\n])\n# Energy usage: higher at peak hours (9am, 6pm), lower at night, higher when hot\ny = (\n    20 + 0.5 * X[:, 0]\n    - 0.1 * X[:, 1]\n    + 8 * np.sin(np.pi * X[:, 2] / 12)\n    + 5 * X[:, 3]\n    + rng.randn(60) * 2\n)\n\n# TODO: Initialize GradientBoostingRegressor(n_estimators=100, learning_rate=0.05, max_depth=4, subsample=0.8, random_state=42)\n# TODO: Compute r2_scores using cross_val_score with cv=5 and scoring='r2'\n# TODO: Fit model on full X, y; predict on X; compute RMSE\nmodel = None\nr2_scores = np.array([])\nrmse = 0.0\n\nprint(f\"Mean R2: {np.round(np.mean(r2_scores), 2)}\")\nprint(f\"RMSE: {np.round(rmse, 2)}\")  ",
      "expectedOutput": "Mean R2: 0.88\nRMSE: 1.25",
      "solution": "import numpy as np\nfrom sklearn.ensemble import GradientBoostingRegressor\nfrom sklearn.model_selection import cross_val_score\nfrom sklearn.metrics import mean_squared_error\n\nrng = np.random.RandomState(42)\nX = np.column_stack([\n    rng.uniform(15, 35, 60),\n    rng.uniform(30, 90, 60),\n    np.tile(np.arange(24), 3)[:60],\n    np.tile([0,0,0,0,0,1,1], 9)[:60]\n])\ny = (\n    20 + 0.5 * X[:, 0]\n    - 0.1 * X[:, 1]\n    + 8 * np.sin(np.pi * X[:, 2] / 12)\n    + 5 * X[:, 3]\n    + rng.randn(60) * 2\n)\n\nmodel = GradientBoostingRegressor(n_estimators=100, learning_rate=0.05, max_depth=4, subsample=0.8, random_state=42)\nr2_scores = cross_val_score(model, X, y, cv=5, scoring='r2')\nmodel.fit(X, y)\npredictions = model.predict(X)\nrmse = np.sqrt(mean_squared_error(y, predictions))\n\nprint(f\"Mean R2: {np.round(np.mean(r2_scores), 2)}\")\nprint(f\"RMSE: {np.round(rmse, 2)}\")",
      "hints": [
        "Initialize GradientBoostingRegressor(n_estimators=100, learning_rate=0.05, max_depth=4, subsample=0.8, random_state=42)",
        "Use cross_val_score(model, X, y, cv=5, scoring='r2') for R² evaluation",
        "Use np.sqrt(mean_squared_error(y, model.predict(X))) for RMSE"
      ],
      "testKeywords": [
        "GradientBoostingRegressor",
        "cross_val_score",
        "mean_squared_error",
        "np.sqrt",
        "fit",
        "predict"
      ]
    }
  },
  "interviewQuestions": [
    {
      "question": "What is the main difference between Bagging (e.g., Random Forest) and Boosting (e.g., Gradient Boosting)?",
      "answer": "Bagging trains deep, high-variance trees independently in parallel and averages their predictions to reduce variance. Boosting trains shallow, high-bias trees sequentially, where each tree corrects the errors of the previous ones to reduce bias.",
      "companyTags": [
        "Amazon",
        "Google",
        "Meta"
      ],
      "difficulty": "Easy"
    },
    {
      "question": "How does Gradient Boosting relate to Gradient Descent?",
      "answer": "Gradient Boosting performs gradient descent in function space. Instead of updating parameters, it updates the model (a function) by adding a new tree that approximates the negative gradient (pseudo-residuals) of the loss function.",
      "companyTags": [
        "Microsoft",
        "DeepMind"
      ],
      "difficulty": "Hard"
    },
    {
      "question": "Explain the concept of 'shrinkage' (learning rate) in Gradient Boosting.",
      "answer": "Shrinkage scales the contribution of each new tree by a factor between 0 and 1. It acts as a regularizer; by taking smaller steps, the model requires more trees to converge, which makes the ensemble generalize better to unseen data.",
      "companyTags": [
        "Netflix",
        "Apple"
      ],
      "difficulty": "Medium"
    },
    {
      "question": "Why is XGBoost often much faster than traditional GBM?",
      "answer": "XGBoost implements a highly optimized, scalable, and distributed gradient boosting system. It parallelizes the tree building process (specifically the node split evaluations), uses cache-aware access, and handles out-of-core computing.",
      "companyTags": [
        "Amazon",
        "Lyft"
      ],
      "difficulty": "Medium"
    },
    {
      "question": "What does it mean that XGBoost uses a second-order Taylor approximation?",
      "answer": "Traditional GBM calculates the first derivative (gradient) of the loss to find pseudo-residuals. XGBoost uses both the first derivative (gradient) and the second derivative (Hessian) to provide a more accurate and faster step towards the minimum loss.",
      "companyTags": [
        "Google",
        "Meta"
      ],
      "difficulty": "Hard"
    },
    {
      "question": "What happens if you run Gradient Boosting for too many iterations?",
      "answer": "Unlike Random Forests, which do not overfit as more trees are added, Gradient Boosting will eventually perfectly fit the training data, capturing noise and causing severe overfitting.",
      "companyTags": [
        "Microsoft",
        "Netflix"
      ],
      "difficulty": "Easy"
    },
    {
      "question": "How can you prevent Gradient Boosting from overfitting?",
      "answer": "Use early stopping on a validation set, decrease the max_depth of trees, use a smaller learning rate, apply row/column subsampling (Stochastic GBM), or increase L1/L2 regularization penalties (in XGBoost).",
      "companyTags": [
        "Amazon",
        "Apple"
      ],
      "difficulty": "Medium"
    },
    {
      "question": "Why are decision stumps or shallow trees (depth 3-6) preferred as weak learners in Boosting?",
      "answer": "Deep trees have low bias but high variance. Boosting inherently reduces bias sequentially, so it starts with high-bias, low-variance models (shallow trees). Deep trees would quickly overfit the residuals.",
      "companyTags": [
        "Meta",
        "Google"
      ],
      "difficulty": "Medium"
    },
    {
      "question": "Can Gradient Boosting handle missing values?",
      "answer": "Standard GBM from scikit-learn generally cannot, but modern implementations like XGBoost and LightGBM handle them inherently by learning a default direction (left or right) for missing values during the split-finding process.",
      "companyTags": [
        "Amazon",
        "Microsoft"
      ],
      "difficulty": "Medium"
    },
    {
      "question": "What is LightGBM and how does it differ from XGBoost?",
      "answer": "LightGBM is a boosting framework developed by Microsoft. Unlike XGBoost, which grows trees level-wise (depth-first), LightGBM grows trees leaf-wise (best-first), which can reduce loss faster but is more prone to overfitting on small datasets.",
      "companyTags": [
        "Microsoft",
        "Meta"
      ],
      "difficulty": "Hard"
    },
    {
      "question": "Explain column subsampling in XGBoost.",
      "answer": "Similar to Random Forests, XGBoost can select a random fraction of features (columns) for each tree or each split. This reduces correlation between trees, prevents overfitting, and speeds up training.",
      "companyTags": [
        "Apple",
        "Netflix"
      ],
      "difficulty": "Medium"
    },
    {
      "question": "How do you tune the learning rate and n_estimators in Gradient Boosting?",
      "answer": "They are inversely related. A common approach is to fix the learning rate to a small value (e.g., 0.05 or 0.1) and use cross-validation with early stopping to find the optimal n_estimators.",
      "companyTags": [
        "Google",
        "Amazon"
      ],
      "difficulty": "Medium"
    },
    {
      "question": "What loss function would you use in Gradient Boosting for an imbalanced binary classification problem?",
      "answer": "You would use Log Loss (Binary Cross-Entropy), but you should adjust the `scale_pos_weight` parameter (in XGBoost) to assign higher weights to the positive minority class, penalizing those errors more heavily.",
      "companyTags": [
        "Meta",
        "Lyft"
      ],
      "difficulty": "Hard"
    },
    {
      "question": "What is CatBoost?",
      "answer": "CatBoost is a boosting algorithm by Yandex optimized for handling categorical features inherently without needing one-hot encoding, using ordered boosting to mitigate target leakage.",
      "companyTags": [
        "Google",
        "DeepMind"
      ],
      "difficulty": "Medium"
    },
    {
      "question": "How are the initial predictions formed in Gradient Boosting for regression?",
      "answer": "The initial prediction F0(x) is usually a constant value that minimizes the loss function. For Mean Squared Error, this is simply the mean of the training target values.",
      "companyTags": [
        "Amazon",
        "Apple"
      ],
      "difficulty": "Medium"
    },
    {
      "question": "Can Gradient Boosting be parallelized?",
      "answer": "The sequential addition of trees cannot be parallelized. However, the process of finding the best split within a single tree (evaluating histograms or exact greedy splits across features) can be and is parallelized in XGBoost/LightGBM.",
      "companyTags": [
        "Microsoft",
        "Meta"
      ],
      "difficulty": "Hard"
    },
    {
      "question": "Explain the exact greedy algorithm for split finding in trees.",
      "answer": "The exact greedy algorithm evaluates every possible split point for every continuous feature by sorting the feature values and calculating the gain. It is highly accurate but computationally expensive for large datasets.",
      "companyTags": [
        "Google",
        "Netflix"
      ],
      "difficulty": "Hard"
    },
    {
      "question": "How do histogram-based algorithms speed up Gradient Boosting?",
      "answer": "Instead of evaluating every single continuous split point, histogram algorithms (used in LightGBM and HistGradientBoosting) bucket continuous features into discrete bins (e.g., 256 bins), dramatically reducing the split evaluation time and memory usage.",
      "companyTags": [
        "Microsoft",
        "Amazon"
      ],
      "difficulty": "Hard"
    },
    {
      "question": "If your Gradient Boosting model has high bias, what hyperparameter changes would you make?",
      "answer": "To reduce bias (underfitting), you should increase the complexity: increase `max_depth`, decrease `min_samples_split`, decrease regularization parameters (L1/L2), or increase `n_estimators`.",
      "companyTags": [
        "Meta",
        "Lyft"
      ],
      "difficulty": "Medium"
    },
    {
      "question": "What does the Gamma parameter do in XGBoost?",
      "answer": "Gamma is a regularization parameter specifying the minimum loss reduction required to make a further partition on a leaf node. It acts as a pseudo-regularizer, controlling the complexity of the tree by preventing arbitrary splits.",
      "companyTags": [
        "Google",
        "Apple"
      ],
      "difficulty": "Hard"
    }
  ]
};
